apiVersion: apps/v1
kind: Deployment
metadata:
 name: my-custome-deployment
 lables:
 app: custom
spec:
 replicas: 2
 selector:
   matchLables:
    app: custom
 template:
   metadata:
    lables:
      app: custom
    spec:
      containers:
      -name: custom
       image: tanishdevops/project2
       ports:
       - containerPost: 80
